### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/gkrellm#1]
Hi @timsan7sk, we need to adjust a few things first to move forward, ok? ✨

We need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute, too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by timsan7sk** [comment]
Hi @luxonauta!
To install theme only need:
```sh
git clone https://github.com/dracula/gkrellm
cp -r gkrellm ~/.gkrellm2/theme/Dracula
```
and it's done.
